Repository TheYuriG/deno-portfolio, pull requests merged in 2023-07, with the labels that each got.

#93 chore: update Fresh to v1.2.0
  components/base/Aside.tsx
  deno.json
  deno.lock
  fresh.gen.ts
  import_map.json
  islands/UI/DigitalTimer.tsx
  islands/misc/Collapsible.tsx
  islands/misc/CopyTextAreaToClipboard.tsx
  islands/misc/FormWithValidation.tsx
  islands/misc/ThemeSwitcher.tsx
  islands/projects/AddNewExpense.tsx
  islands/projects/ExpensesTracker.tsx
  islands/projects/ExpensesYearSelect.tsx
  islands/projects/FoodOrder.tsx
  islands/projects/FoodOrderCheckout.tsx
  islands/tools/HighlightedCode.tsx
  islands/tools/RetirementCalculationForm.tsx
  islands/tools/RetirementCalculator.tsx
  islands/tools/WhatsappLinkGenerator.tsx
  islands/toys/InsanitySection.tsx
  routes/projects/expenses-tracker.tsx
  routes/projects/food-order/checkout.tsx
  routes/projects/food-order/index.tsx
  routes/projects/food-order/success.tsx
  routes/tools/highlighted-text/[text].tsx
  routes/tools/retirement-calculator.tsx
  routes/tools/whatsapp-message-link-generator.tsx
  routes/toys/insanity.tsx
  routes/work/form.tsx
Labels: Internal

#95 fix: Modal will not allow background to scroll while active
  components/UI/ModalExtendedImage.tsx
  components/UI/ModalWithBackdrop.tsx
  components/projects/food-order/CartModal.tsx
  fresh.gen.ts
  islands/UI/Modal.tsx
  islands/misc/Collapsible.tsx
  islands/projects/FoodOrder.tsx
  routes/projects/expenses-tracker.tsx
  routes/projects/food-order/index.tsx
Labels: User Experience

#96 chore: updated text in /work and /projects
  components/projects/ProjectsGrid.tsx
  fresh.gen.ts
  islands/projects/FormWithValidation.tsx
  routes/projects/index.tsx
  routes/projects/stimulus-check.tsx
  routes/work/index.tsx
Labels: User Experience, Internal

#101 feat: save whatsapp link generator data to localStorage
  components/UI/StyledInput.tsx
  islands/projects/ExpensesTracker.tsx
  islands/projects/FoodOrder.tsx
  islands/tools/WhatsappLinkGenerator.tsx
Labels: Enhancement

#102 feat: allow users to set and use variables on their whatsapp message links
  components/tools/WhatsappLinksList.tsx
  components/tools/WhatsappMessagePreview.tsx
  data/tools/whatsapp-link-generator/whatsapp-message-missing-variable.ts
  data/tools/whatsapp-link-generator/whatsapp-message-variable-placeholder.ts
  islands/tools/WhatsappLinkGenerator.tsx
  types/component-properties/tools/whatsapp-link-generator/whatsapp-link-data.ts
Labels: Enhancement, User Experience

#109 feat: add blog post about my experience with the Deno runtime
  components/UI/GreekList.tsx
  data/blog/experience-deno-fresh.ts
  fresh.gen.ts
  routes/blog/experience-deno-fresh.tsx
  routes/blog/index.tsx
  static/sitemap.xml
  twind.config.ts
Labels: Enhancement, User Experience

#110 fix: wave emoji activates on name hover
  components/UI/StyledHeader.tsx
  components/UI/StyledSubHeader.tsx
  components/blog/BlogPostFooter.tsx
  components/blog/BlogPostSummary.tsx
  components/home/HomeContent.tsx
  routes/blog/experience-deno-fresh.tsx
  routes/blog/how-create-categories-discord-v14.tsx
  routes/blog/how-create-roles-discord-v14.tsx
  routes/blog/how-create-text-channels-discord-v14.tsx
  routes/blog/how-create-theme-switcher-deno-fresh.tsx
  routes/blog/how-create-voice-channels-discord-v14.tsx
  routes/blog/stopping-theme-flickering-deno-fresh.tsx
  static/themeSwitcherMinified.js
Labels: Bug, Enhancement, User Experience, Internal

#111 refactor: only use GradientLink for external links
  assets/ExternalLinkIcon.tsx
  components/UI/DottedLink.tsx
  components/UI/GradientLink.tsx
  components/home/HomeContent.tsx
  components/tools/WhatsappLinksList.tsx
  routes/blog/experience-deno-fresh.tsx
  routes/blog/how-create-categories-discord-v14.tsx
  routes/blog/how-create-roles-discord-v14.tsx
  routes/blog/how-create-text-channels-discord-v14.tsx
  routes/blog/how-create-theme-switcher-deno-fresh.tsx
  routes/blog/how-create-voice-channels-discord-v14.tsx
  routes/certificates.tsx
  routes/projects/index.tsx
  routes/tools/index.tsx
  routes/what-is-this.tsx
  routes/work/index.tsx
  types/component-properties/DecoratedLinkProperties.ts
Labels: User Experience, Internal

#114 prototype: adds attempt at python/javascript syntax comparison blog post
  components/UI/CountryPhoneCodeSelect.tsx
  components/UI/StyledInput.tsx
  components/UI/Tooltip.tsx
  components/blog/ComparisonTable.tsx
  components/home/HomeContent.tsx
  components/tools/expression-visualizer/ExpressionVisualizationListItem.tsx
  components/tools/retirement-calculator/RetirementCalculationTable.tsx
  components/tools/syntax-highlight/SyntaxHighlighForm.tsx
  components/tools/whatsapp-message-link-generator/WhatsappLinksList.tsx
  components/tools/whatsapp-message-link-generator/WhatsappMessagePreview.tsx
  data/blog/javascript-python-syntax.ts
  fresh.gen.ts
  islands/tools/ExpressionVisualizationList.tsx
  islands/tools/RetirementCalculator.tsx
  islands/tools/WhatsappLinkGenerator.tsx
  routes/blog/index.tsx
  routes/blog/javascript-python-syntax.tsx
  routes/tools/syntax-highlight.tsx
  static/sitemap.xml
Labels: Enhancement, User Experience

#115 feat: add tictactoe project sent by WeekendWebDev :)
  assets/CircleIcon.tsx
  assets/XMarkIcon.tsx
  components/projects/ProjectsGrid.tsx
  components/projects/tictactoe/TicTacToeGameStatus.tsx
  components/projects/tictactoe/TicTacToeTile.tsx
  data/projects/tictactoe/maxTiles.ts
  fresh.gen.ts
  islands/projects/TicTacToeBoard.tsx
  routes/projects/expenses-tracker.tsx
  routes/projects/food-order/index.tsx
  routes/projects/index.tsx
  routes/projects/stimulus-check.tsx
  routes/projects/tictactoe.tsx
  services/tictactoe/changePlayers.ts
  services/tictactoe/resetBoardFunction.ts
  services/tictactoe/shouldGameEnd.ts
  types/component-properties/projects/tictactoe/BoardTile.ts
Labels: Enhancement

#117 Responsive Comparison Table and README Link Fix
  README.md
  components/blog/ComparisonTable.tsx
  components/tools/retirement-calculator/RetirementCalculationTable.tsx
  routes/blog/javascript-python-syntax.tsx
Labels: User Experience

#119 feat: added Python automation certificate
  routes/certificates.tsx
Labels: Enhancement, User Experience
